"""场景 -> 自包含 pytest 固化脚本。

API 步骤编译为确定性代码；UI 步骤生成带指令注释的 NotImplementedError 占位，
由 Agent（参照 .claude/skills/atk-smoke）填充后用 atk doctor 分类校验。
产物仅依赖 httpx + pytest，不 import atk。
"""
import re
from pathlib import Path

import yaml

from ..executors.env import substitute
from ..store.models import ApiStep, UiStep

_VAR = re.compile(r"\$\{(\w+)\}")

_HEADER = '''"""AUTO-GENERATED by atk export — DO NOT EDIT.
Source: {src}
Regenerate: atk export {src}
"""
import httpx

BASE_URL = {base_url!r}
TIMEOUT = 30.0

_MISSING = object()


def _path(d, dotted):
    cur = d
    for seg in str(dotted).split("."):
        try:
            cur = cur[int(seg)] if seg.isdigit() else cur[seg]
        except (KeyError, IndexError, TypeError):
            return _MISSING
    return cur


def _client():
    return httpx.Client(base_url=BASE_URL, timeout=TIMEOUT, trust_env=False)


def _expect_status(resp, want):
    assert resp.status_code == want, f"status 期望 {{want}} 实际 {{resp.status_code}}"


def _expect_ok(resp):
    assert resp.status_code < 400, f"未显式断言 status，隐式要求 <400，实际 {{resp.status_code}}"


def _expect_eq(j, dotted, want):
    got = _path(j, dotted)
    assert got is not _MISSING, f"{{dotted}} 缺失"
    assert got == want, f"{{dotted}} 期望 {{want!r}} 实际 {{got!r}}"


def _expect_not_null(j, dotted):
    v = _path(j, dotted)
    assert v is not _MISSING and v is not None and v != "", f"{{dotted}} 为空或缺失"

'''


def _slug(name: str, fallback: str) -> str:
    s = "".join(ch if ch.isascii() and ch.isalnum() else "_" for ch in name).strip("_")
    s = re.sub(r"_+", "_", s) or fallback
    if s[0].isdigit():
        s = "t_" + s
    return s


def _gen_str(s: str, captured: set[str], variables: dict):
    """返回 python 字面量；含已捕获变量的串转 f-string，其余导出期解析。"""
    resolved = substitute(s, variables)
    if not isinstance(resolved, str):
        return _pylit(resolved)  # 整串命中变量且值为非字符串
    live = (set(_VAR.findall(s)) | set(_VAR.findall(resolved))) & captured
    if live:
        body = _VAR.sub(lambda m: "{" + m.group(1) + "}", resolved)
        return f"f{_pylit(body)}"
    return _pylit(resolved)


def _pylit(v):
    return repr(v)


def _walk(v, captured: set[str], variables: dict):
    if isinstance(v, str):
        return _gen_str(v, captured, variables)
    if isinstance(v, dict):
        items = ", ".join(f"{_pylit(k)}: {_walk(x, captured, variables)}" for k, x in v.items())
        return "{" + items + "}"
    if isinstance(v, list):
        return "[" + ", ".join(_walk(x, captured, variables) for x in v) + "]"
    return _pylit(v)


def _compile_api(i: int, st: ApiStep, captured: set[str], variables: dict) -> list[str]:
    method, _, raw_path = st.call.partition(" ")
    lines: list[str] = []
    path_expr = _gen_str(raw_path.strip(), captured, variables)
    args = [f"{method.upper()!r}", path_expr]
    if st.headers:
        args.append(f"headers={_walk(st.headers, captured, variables)}")
    if st.body is not None:
        args.append(f"json={_walk(st.body, captured, variables)}")
    lines.append(f"        r{i} = c.request({', '.join(args)})")
    has_status = any(e.status is not None for e in st.expect)
    need_json = any(e.path is not None for e in st.expect) or bool(st.capture)
    if has_status:
        lines.append(f"        _expect_status(r{i}, {next(e.status for e in st.expect if e.status is not None)})")
    else:
        lines.append(f"        _expect_ok(r{i})")
    if need_json:
        lines.append(f"        j{i} = r{i}.json()")
    for e in st.expect:
        if e.status is not None:
            continue
        if e.op == "not_null":
            lines.append(f"        _expect_not_null(j{i}, {_pylit(e.path)})")
        else:
            lines.append(f"        _expect_eq(j{i}, {_pylit(e.path)}, {_pylit(e.value)})")
    for var, dotted in st.capture.items():
        lines.append(f"        {var} = _path(j{i}, {_pylit(dotted)})")
        captured.add(var)
    return lines


def export_scenario(
    src: Path | str,
    out_dir: Path | str,
    base_url: str,
    variables: dict | None = None,
) -> Path:
    """把单个场景 YAML 编译为 generated/ 下自包含 pytest 文件。"""
    src = Path(src)
    raw = yaml.safe_load(src.read_text(encoding="utf-8"))
    sc_file = src.as_posix()
    from ..store.models import Scenario

    sc = Scenario.from_raw(raw, file=sc_file)
    variables = dict(variables or {})
    captured: set[str] = set()
    lines: list[str] = [
        f"def test_{_slug(sc.scenario, src.stem)}():",
        "    with _client() as c:",
    ]
    idx = 0
    for st in sc.steps:
        if isinstance(st, ApiStep):
            lines += _compile_api(idx, st, captured, variables)
            idx += 1
        else:
            action = substitute(st.action, variables)
            expect = substitute(st.expect or "", variables) if st.expect else ""
            lines += [
                "",
                f"        # TODO(agent): 固化下述 UI 步骤为确定性操作后删除 raise",
                f"        #   操作: {action}",
                f"        #   断言: {expect}",
                f'        raise NotImplementedError("UI step pending solidify: {action}")',
            ]
    if not sc.steps:
        lines.append("    raise AssertionError('场景无步骤')")
    header = _HEADER.format(src=sc_file, base_url=base_url)
    out_path = Path(out_dir) / f"test_{_slug(sc.scenario, src.stem)}.py"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(header + "\n" + "\n".join(lines) + "\n", encoding="utf-8")
    return out_path
